# Generated by Django 4.1.7 on 2023-02-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confession_for', models.CharField(blank=True, max_length=256, null=True)),
                ('confession_note', models.TextField(blank=True, max_length=5120, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=128, null=True)),
                ('sender_info', models.TextField(blank=True, max_length=512, null=True)),
                ('state', models.CharField(blank=True, default='new', max_length=16, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_star', models.BooleanField(default=False)),
                ('likes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('comment_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=512, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('confession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.confession')),
            ],
        ),
    ]
