# Generated by Django 4.1.7 on 2023-03-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confession',
            old_name='confession_for',
            new_name='confession_title',
        ),
    ]
