# Generated by Django 4.1.7 on 2023-03-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_confession_for_confession_confession_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='likes',
        ),
    ]
